In [2]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("Creditcard_data.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [8]:
df["Class"].value_counts()

0    763
1      9
Name: Class, dtype: int64

In [9]:
class_0 = df[df['Class'] == 0]
class_1 = df[df['Class'] == 1]
print('class 0:', class_0.shape)
print('class 1:', class_1.shape)

class 0: (763, 31)
class 1: (9, 31)

In [16]:
X=df.drop("Class",axis=1)
Y=df["Class"]

In [ ]:
# #Random Over-Sampling
# from sklearn.ensemble import RandomForestClassifier
# from imblearn.over_sampling import RandomOverSampler
# from sklearn.model_selection import cross_val_score, KFold
# from sklearn.metrics import classification_report
# cv = KFold(n_splits=5, shuffle=True, random_state=42)

# rf = RandomForestClassifier(n_estimators=100, random_state=42)
# for train_index, test_index in cv.split(X, Y):
#     # Split the data into training and testing sets for this fold
#     X_train, X_test = X.iloc[train_index], X.iloc[test_index]
#     y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    
#     # Apply SMOTE to oversample the minority class in the training set for this fold
#     ros = RandomOverSampler(random_state=42)

#     X_train_resampled, y_train_resampled = ros.fit_resample(X_train, y_train)
#     print(y_train.value_counts(),y_train_resampled.value_counts())
#     # # Train the model on the resampled training set for this fold
#     rf.fit(X_train_resampled, y_train_resampled)
    
#     # # Make predictions on the testing set for this fold
#     y_pred = rf.predict(X_test)
    
#     # # Evaluate the model performance for this fold
#     print(classification_report(y_test, y_pred))

In [27]:
scores = cross_val_score(rf, X, Y, cv=cv, scoring='accuracy')
print(scores)

[0.99354839 0.96774194 0.99350649 1.         0.98701299]

In [52]:
# Importing required libraries
import pandas as pd
from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN
from sklearn.model_selection import cross_val_score, KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Load the data
data = pd.read_csv('Creditcard_data.csv')

# Separate the features and target variable
X = data.drop('Class', axis=1)
y = data['Class']

# Define the sampling techniques
ros = RandomOverSampler(random_state=42)
sm = SMOTE(random_state=42)
ada = ADASYN(random_state=42)

# Define the random forest classifier model
rf = RandomForestClassifier(n_estimators=100, random_state=42)


for sampler in [ros, sm, ada]:
    skf = StratifiedKFold(n_splits=5)
    for i, (train_index, test_index) in enumerate(skf.split(X, y)):
        
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        # sampling technique to the training 
        X_train_resampled, y_train_resampled = sampler.fit_resample(X_train, y_train)


        rf.fit(X_train_resampled, y_train_resampled)

       
        y_pred = rf.predict(X_test)
        
        
    # cross-validation score for this sampling technique
    scores = cross_val_score(rf, X, y, cv=skf, scoring='accuracy')
    print(f'score for {type(sampler).__name__}: {scores}')

score for RandomOverSampler: [0.98709677 0.98709677 0.99350649 0.98701299 0.98701299]
score for SMOTE: [0.98709677 0.98709677 0.99350649 0.98701299 0.98701299]
score for ADASYN: [0.98709677 0.98709677 0.99350649 0.98701299 0.98701299]

In [ ]:
import pandas as pd
import numpy as np
from imblearn.under_sampling import RandomUnderSampler
from imblearn.under_sampling import TomekLinks
from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN, BorderlineSMOTE, SVMSMOTE,KMeansSMOTE
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.metrics import classification_report
# Define the sampling techniques
samplers = [RandomOverSampler(random_state=42), SMOTE(random_state=42), 
            ADASYN(random_state=42), BorderlineSMOTE(random_state=42),
            TomekLinks(),
            RandomUnderSampler(random_state=42)
            ]
ans=[]

# Define the models
models = [LogisticRegression(solver='lbfgs',max_iter=1000), DecisionTreeClassifier(max_depth=10), RandomForestClassifier(n_estimators=100), GradientBoostingClassifier(), AdaBoostClassifier()]
results = pd.DataFrame()
# results.head()
# Define the cross-validation object
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
f1_scores = {}
# cv = KFold(n_splits=5, shuffle=True)
# Iterate over the sampling techniques and the data splits
for sampler in samplers:
    for model in models:
        model_scores = {}
        for i, (train_index, test_index) in enumerate(cv.split(X, y)):
            # Split the data into training and testing sets for this fold
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train, y_test = y.iloc[train_index], y.iloc[test_index]

            # Apply the sampling technique to the training set for this fold
            X_train_resampled, y_train_resampled = sampler.fit_resample(X_train, y_train)

            # Train the model on the resampled training set for this fold
            model.fit(X_train_resampled, y_train_resampled)

            # Evaluate the model performance on the testing set for this fold using classification report
            y_pred = model.predict(X_test)
            # print(f'{type(model).__name__} using {type(sampler).__name__}, fold {i+1}:')
            # print(classification_report(y_test, y_pred))
            
        # Compute the average cross-validation score for this model and sampling technique
        scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy')
        ans.append(f'Average accuracy score for {type(model).__name__} using {type(sampler).__name__}: {scores.mean():.4f}')
        results.loc[f'{type(model).__name__}', f'{type(sampler).__name__}'] = f'{scores.mean():.5f}'
        # print(f'Average f1_macro score for {type(model).__name__} using {type(sampler).__name__}: {scores.mean():.4f}')

In [67]:
results

,RandomOverSampler,SMOTE,ADASYN,BorderlineSMOTE,TomekLinks,RandomUnderSampler
LogisticRegression,0.98705,0.98705,0.98705,0.98705,0.98705,0.98705
DecisionTreeClassifier,0.97538,0.98056,0.98185,0.98187,0.97410,0.98185
RandomForestClassifier,0.98835,0.98835,0.98835,0.98835,0.98835,0.98835
GradientBoostingClassifier,0.98445,0.98445,0.98445,0.98445,0.98575,0.98705
AdaBoostClassifier,0.98705,0.98705,0.98575,0.98705,0.98705,0.98705

In [68]:
results.max()

RandomOverSampler     0.98835
SMOTE                 0.98835
ADASYN                0.98835
BorderlineSMOTE       0.98835
TomekLinks            0.98835
RandomUnderSampler    0.98835
dtype: object